# [START class]
POST /walletobjects/v1/transitClass HTTP/1.1
Host: walletobjects.googleapis.com
Content-Type: application/json
Authorization: Bearer ACCESS_TOKEN;
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: Keep-Alive

{
  "id": "ISSUER_ID.CLASS_SUFFIX",
  "issuerName": "Issuer name",
  "reviewStatus": "UNDER_REVIEW",
  "logo": {
    "sourceUri": {
      "uri": "https://live.staticflickr.com/65535/48690277162_cd05f03f4d_o.png"
    },
    "contentDescription": {
      "defaultValue": {
        "language": "en-US",
        "value": "Logo description"
      }
    }
  },
  "transitType": "BUS"
}
# [END class]

# [START object]
POST /walletobjects/v1/transitObject HTTP/1.1
Host: walletobjects.googleapis.com
Content-Type: application/json
Authorization: Bearer ACCESS_TOKEN;
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: Keep-Alive

{
  "id": "ISSUER_ID.OBJECT_ID",
  "classId": "ISSUER_ID.CLASS_SUFFIX",
  "state": "ACTIVE",
  "heroImage": {
    "sourceUri": {
      "uri": "https://farm4.staticflickr.com/3723/11177041115_6e6a3b6f49_o.jpg"
    },
    "contentDescription": {
      "defaultValue": {
        "language": "en-US",
        "value": "Hero image description"
      }
    }
  },
  "textModulesData": [
    {
      "header": "Text module header",
      "body": "Text module body",
      "id": "TEXT_MODULE_ID"
    }
  ],
  "linksModuleData": {
    "uris": [
      {
        "uri": "http://maps.google.com/",
        "description": "Link module URI description",
        "id": "LINK_MODULE_URI_ID"
      },
      {
        "uri": "tel:6505555555",
        "description": "Link module tel description",
        "id": "LINK_MODULE_TEL_ID"
      }
    ]
  },
  "imageModulesData": [
    {
      "mainImage": {
        "sourceUri": {
          "uri": "http://farm4.staticflickr.com/3738/12440799783_3dc3c20606_b.jpg"
        },
        "contentDescription": {
          "defaultValue": {
            "language": "en-US",
            "value": "Image module description"
          }
        }
      },
      "id": "IMAGE_MODULE_ID"
    }
  ],
  "barcode": {
    "type": "QR_CODE",
    "value": "QR code"
  },
  "locations": [
    {
      "latitude": 37.424015499999996,
      "longitude": -122.09259560000001
    }
  ],
  "passengerType": "SINGLE_PASSENGER",
  "passengerNames": "Passenger names",
  "tripType": "ONE_WAY",
  "ticketLeg": {
    "originStationCode": "LA",
    "originName": {
      "defaultValue": {
        "language": "en-US",
        "value": "Origin name"
      }
    },
    "destinationStationCode": "SFO",
    "destinationName": {
      "defaultValue": {
        "language": "en-US",
        "value": "Destination name"
      }
    },
    "departureDateTime": "2020-04-12T16:20:50.52Z",
    "arrivalDateTime": "2020-04-12T20:20:50.52Z",
    "fareName": {
      "defaultValue": {
        "language": "en-US",
        "value": "Fare name"
      }
    }
  }
}
# [END object]

# [START createIssuer]
POST /walletobjects/v1/issuer HTTP/1.1
Host: walletobjects.googleapis.com
Content-Type: application/json
Authorization: Bearer ACCESS_TOKEN;
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: Keep-Alive

{
  "name": "ISSUER_NAME",
  "contactInfo": {
    "email": "ISSUER_EMAIL"
  }
}
# [END createIssuer]

# [START updatePermissions]
PUT /walletobjects/v1/permissions/ISSUER_ID HTTP/1.1
Host: walletobjects.googleapis.com
Content-Type: application/json
Authorization: Bearer ACCESS_TOKEN;
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: Keep-Alive

{
  "issuerId": "ISSUER_ID",
  "permissions": [
    {
      emailAddress = "EMAIL_ADDRESS",
      role = "READER | WRITER | OWNER"
    }
  ]
}
# [END updatePermissions]

# [START batch]
POST /batch HTTP/1.1
Host: walletobjects.googleapis.com
Content-Type: multipart/mixed; boundary=batch_createobjectbatch
Authorization: Bearer ACCESS_TOKEN
Content-Length: TOTAL_CONTENT_LENGTH

--batch_createobjectbatch
Content-Type: application/json

POST /walletobjects/v1/transitObject/

{
  "id": "ISSUER_ID.OBJECT_ID",
  "classId": "ISSUER_ID.CLASS_SUFFIX",
  "state": "ACTIVE",
  "heroImage": {
    "sourceUri": {
      "uri": "https://farm4.staticflickr.com/3723/11177041115_6e6a3b6f49_o.jpg"
    },
    "contentDescription": {
      "defaultValue": {
        "language": "en-US",
        "value": "Hero image description"
      }
    }
  },
  "textModulesData": [
    {
      "header": "Text module header",
      "body": "Text module body",
      "id": "TEXT_MODULE_ID"
    }
  ],
  "linksModuleData": {
    "uris": [
      {
        "uri": "http://maps.google.com/",
        "description": "Link module URI description",
        "id": "LINK_MODULE_URI_ID"
      },
      {
        "uri": "tel:6505555555",
        "description": "Link module tel description",
        "id": "LINK_MODULE_TEL_ID"
      }
    ]
  },
  "imageModulesData": [
    {
      "mainImage": {
        "sourceUri": {
          "uri": "http://farm4.staticflickr.com/3738/12440799783_3dc3c20606_b.jpg"
        },
        "contentDescription": {
          "defaultValue": {
            "language": "en-US",
            "value": "Image module description"
          }
        }
      },
      "id": "IMAGE_MODULE_ID"
    }
  ],
  "barcode": {
    "type": "QR_CODE",
    "value": "QR code"
  },
  "locations": [
    {
      "latitude": 37.424015499999996,
      "longitude": -122.09259560000001
    }
  ],
  "passengerType": "SINGLE_PASSENGER",
  "passengerNames": "Passenger names",
  "tripType": "ONE_WAY",
  "ticketLeg": {
    "originStationCode": "LA",
    "originName": {
      "defaultValue": {
        "language": "en-US",
        "value": "Origin name"
      }
    },
    "destinationStationCode": "SFO",
    "destinationName": {
      "defaultValue": {
        "language": "en-US",
        "value": "Destination name"
      }
    },
    "departureDateTime": "2020-04-12T16:20:50.52Z",
    "arrivalDateTime": "2020-04-12T20:20:50.52Z",
    "fareName": {
      "defaultValue": {
        "language": "en-US",
        "value": "Fare name"
      }
    }
  }
}

--batch_createobjectbatch
Content-Type: application/json

POST /walletobjects/v1/transitObject/

{
  "id": "ISSUER_ID.OBJECT_ID",
  "classId": "ISSUER_ID.CLASS_SUFFIX",
  "state": "ACTIVE",
  "heroImage": {
    "sourceUri": {
      "uri": "https://farm4.staticflickr.com/3723/11177041115_6e6a3b6f49_o.jpg"
    },
    "contentDescription": {
      "defaultValue": {
        "language": "en-US",
        "value": "Hero image description"
      }
    }
  },
  "textModulesData": [
    {
      "header": "Text module header",
      "body": "Text module body",
      "id": "TEXT_MODULE_ID"
    }
  ],
  "linksModuleData": {
    "uris": [
      {
        "uri": "http://maps.google.com/",
        "description": "Link module URI description",
        "id": "LINK_MODULE_URI_ID"
      },
      {
        "uri": "tel:6505555555",
        "description": "Link module tel description",
        "id": "LINK_MODULE_TEL_ID"
      }
    ]
  },
  "imageModulesData": [
    {
      "mainImage": {
        "sourceUri": {
          "uri": "http://farm4.staticflickr.com/3738/12440799783_3dc3c20606_b.jpg"
        },
        "contentDescription": {
          "defaultValue": {
            "language": "en-US",
            "value": "Image module description"
          }
        }
      },
      "id": "IMAGE_MODULE_ID"
    }
  ],
  "barcode": {
    "type": "QR_CODE",
    "value": "QR code"
  },
  "locations": [
    {
      "latitude": 37.424015499999996,
      "longitude": -122.09259560000001
    }
  ],
  "passengerType": "SINGLE_PASSENGER",
  "passengerNames": "Passenger names",
  "tripType": "ONE_WAY",
  "ticketLeg": {
    "originStationCode": "LA",
    "originName": {
      "defaultValue": {
        "language": "en-US",
        "value": "Origin name"
      }
    },
    "destinationStationCode": "SFO",
    "destinationName": {
      "defaultValue": {
        "language": "en-US",
        "value": "Destination name"
      }
    },
    "departureDateTime": "2020-04-12T16:20:50.52Z",
    "arrivalDateTime": "2020-04-12T20:20:50.52Z",
    "fareName": {
      "defaultValue": {
        "language": "en-US",
        "value": "Fare name"
      }
    }
  }
}

--batch_createobjectbatch
Content-Type: application/json

POST /walletobjects/v1/transitObject/

{
  "id": "ISSUER_ID.OBJECT_ID",
  "classId": "ISSUER_ID.CLASS_SUFFIX",
  "state": "ACTIVE",
  "heroImage": {
    "sourceUri": {
      "uri": "https://farm4.staticflickr.com/3723/11177041115_6e6a3b6f49_o.jpg"
    },
    "contentDescription": {
      "defaultValue": {
        "language": "en-US",
        "value": "Hero image description"
      }
    }
  },
  "textModulesData": [
    {
      "header": "Text module header",
      "body": "Text module body",
      "id": "TEXT_MODULE_ID"
    }
  ],
  "linksModuleData": {
    "uris": [
      {
        "uri": "http://maps.google.com/",
        "description": "Link module URI description",
        "id": "LINK_MODULE_URI_ID"
      },
      {
        "uri": "tel:6505555555",
        "description": "Link module tel description",
        "id": "LINK_MODULE_TEL_ID"
      }
    ]
  },
  "imageModulesData": [
    {
      "mainImage": {
        "sourceUri": {
          "uri": "http://farm4.staticflickr.com/3738/12440799783_3dc3c20606_b.jpg"
        },
        "contentDescription": {
          "defaultValue": {
            "language": "en-US",
            "value": "Image module description"
          }
        }
      },
      "id": "IMAGE_MODULE_ID"
    }
  ],
  "barcode": {
    "type": "QR_CODE",
    "value": "QR code"
  },
  "locations": [
    {
      "latitude": 37.424015499999996,
      "longitude": -122.09259560000001
    }
  ],
  "passengerType": "SINGLE_PASSENGER",
  "passengerNames": "Passenger names",
  "tripType": "ONE_WAY",
  "ticketLeg": {
    "originStationCode": "LA",
    "originName": {
      "defaultValue": {
        "language": "en-US",
        "value": "Origin name"
      }
    },
    "destinationStationCode": "SFO",
    "destinationName": {
      "defaultValue": {
        "language": "en-US",
        "value": "Destination name"
      }
    },
    "departureDateTime": "2020-04-12T16:20:50.52Z",
    "arrivalDateTime": "2020-04-12T20:20:50.52Z",
    "fareName": {
      "defaultValue": {
        "language": "en-US",
        "value": "Fare name"
      }
    }
  }
}

--batch_createobjectbatch--
# [END batch]
