# [START object]
POST /walletobjects/v1/$object_typeObject HTTP/1.1
Host: walletobjects.googleapis.com
Content-Type: application/json
Authorization: Bearer <ACCESS_TOKEN>;
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: Keep-Alive

$object_payload
# [END object]

# [START createIssuer]
POST /walletobjects/v1/issuer HTTP/1.1
Host: walletobjects.googleapis.com
Content-Type: application/json
Authorization: Bearer <ACCESS_TOKEN>;
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: Keep-Alive

{
  "name": "<var>name</var>",
  "contactInfo": {
    "email": "<var>email-address</var>"
  }
}
# [END createIssuer]

# [START updatePermissions]
PUT /walletobjects/v1/permissions/<var>issuer-id</var> HTTP/1.1
Host: walletobjects.googleapis.com
Content-Type: application/json
Authorization: Bearer <ACCESS_TOKEN>;
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: Keep-Alive

{
  "issuerId": "<var>issuer-id</var>",
  "permissions": [
    {
      emailAddress = "<var>email-address</var>",
      role = "<var>READER | WRITER | OWNER</var>"
    }
  ]
}
# [END updatePermissions]
